# Generated by Django 5.0.8 on 2026-09-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of key features'),
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions',
            field=models.JSONField(blank=True, default=list, help_text='List of solutions provided'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, help_text='URL to project image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, help_text='List of technologies used'),
        ),
    ]
