# Generated by Django 5.0.8 on 2026-09-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_project_features_project_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cloudinary_image',
            field=models.URLField(blank=True, help_text='Cloudinary image URL', max_length=500, null=True),
        ),
    ]
