"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY') or os.getenv('Django_Key') or 'django-insecure-zsyio-render-fallback-secret-key-prod-94827361'


# Specific allowed hosts configuration
ALLOWED_HOSTS_ENV = os.getenv('ALLOWED_HOSTS')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS_ENV.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        '[::1]',
        'testserver',
        'zsyio.com',
        'www.zsyio.com',
        'company-sites11.vercel.app',
        '.onrender.com',
        '.netlify.app',
    ]

# Security Headers & Hardening (Prevent XSS, Clickjacking, MIME-Sniffing)
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# HTTPS Cookies & Transport Security
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', str(not DEBUG)).lower() == 'true'
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', str(not DEBUG)).lower() == 'true'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# SSL Redirect & HSTS (Enable in production environment with HTTPS)
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
SECURE_HSTS_SECONDS = 31536000 if (not DEBUG and os.getenv('SECURE_HSTS', 'False').lower() == 'true') else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG and SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = not DEBUG and SECURE_HSTS_SECONDS > 0

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://zsyio-company-2-wlgt.onrender.com",
    "https://zsyio-company-1-4qcq.onrender.com",
    "https://*.netlify.app",
    "https://zsyio.com",
    "https://www.zsyio.com",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://company-sites11.vercel.app"
]

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://zsyio.com",
    "https://www.zsyio.com",
    "https://company-sites11.vercel.app",
    "https://zsyio-company-2-wlgt.onrender.com",
    "https://zsyio-company-1-4qcq.onrender.com"
]

# Allow Netlify preview and Render.com deployments via regex
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"https://.*\.netlify\.app$",
    r"https://.*\.onrender\.com$",
]

# Allow credentials (cookies, auth headers) to be sent cross-origin
CORS_ALLOW_CREDENTIALS = True

# Set to True temporarily to solve connectivity issues; set False in strict production
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL', 'True') == 'True'

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]



# Application definition

INSTALLED_APPS = [
    'cloudinary_storage',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'cloudinary',
    # Local apps
    'apps.projects',
    'apps.products',
    'apps.services',
    'apps.about',
    'apps.contact',
    'apps.config_api',
    'apps.estimation',
    'apps.chatbot',
    'apps.authentication',
    'apps.cart',
    'apps.cloudinary_upload',
    'apps.theme',
    'apps.colors',
    'apps.newsletter',
    'apps.careers',
    'apps.insights',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Disable migrations for all apps to silence the "unapplied migrations" warning
# in this mock MongoDB environment.
MIGRATION_MODULES = {
    'admin': 'apps.no_migrations',
    'auth': 'apps.no_migrations',
    'contenttypes': 'apps.no_migrations',
    'sessions': 'apps.no_migrations',
    'messages': 'apps.no_migrations',
    'about': 'apps.no_migrations',
    'cart': 'apps.no_migrations',
    'chatbot': 'apps.no_migrations',
    'config_api': 'apps.no_migrations',
    'estimation': 'apps.no_migrations',
    'projects': 'apps.no_migrations',
    'products': 'apps.no_migrations',
    'services': 'apps.no_migrations',
    'authentication': 'apps.no_migrations',
    'contact': 'apps.no_migrations',
    'theme': 'apps.no_migrations',
    'colors': 'apps.no_migrations',
    'newsletter': 'apps.no_migrations',
    'careers': 'apps.no_migrations',
    'insights': 'apps.no_migrations',
}


# Database configuration
# This project is configured to use ONLY MongoDB.
# We use a custom 'mongodb_mock' engine to satisfy Django's requirements
# while performing actual data operations via pymongo in views.
DATABASES = {
    'default': {
        'ENGINE': 'mongodb_mock',
        'NAME': 'zsyio_db',
        'ENFORCE_SCHEMA': False,
    }
}

import pymongo
MONGO_URI = os.getenv("MONGO_URI")
if MONGO_URI:
    try:
        MONGO_CLIENT = pymongo.MongoClient(
            MONGO_URI, 
            serverSelectionTimeoutMS=5000, 
            tlsAllowInvalidCertificates=True
        )
        # Verify connection
        MONGO_CLIENT.admin.command('ismaster')
        print("MongoDB Connected Successfully")
    except Exception as e:
        print(f"MongoDB Connection Failed: {e}")
        MONGO_CLIENT = None
else:
    print("MONGO_URI not set (skipping MongoDB connection)")
    MONGO_CLIENT = None


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Use CompressedStaticFilesStorage to prevent 500 errors on missing files during collectstatic
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Emails allowed to log in via the API
ALLOWED_LOGIN_EMAILS = [
    "praful@zsyio.com",
    "abhishek@zsyio.com",
    "ashutosh@zsyio.com",
    "ayan@zsyio.com",
    "arpit@zsyio.com",
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'SIGNING_KEY': os.getenv('JWT_SECRET_KEY') or SECRET_KEY,
}

RESEND_API_KEY = os.getenv('RESEND_API_KEY')
RESEND_FROM_EMAIL = os.getenv('RESEND_FROM_EMAIL')
RESEND_ADMIN_EMAIL = os.getenv('RESEND_ADMIN_EMAIL')

APPEND_SLASH = True

# Cloudinary Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET')
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


