services:
  - type: web
    name: zsyio-backend
    env: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: RENDER
        value: "true"
