# Generated by Django 5.0.8 on 2025-12-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=100)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gradient', models.CharField(default='from-[#97DFFC] to-[#8EB5F0]', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Databases', 'Databases'), ('Cloud Solutions', 'Cloud Solutions')], max_length=50)),
                ('icon', models.CharField(help_text='icon name', max_length=100)),
                ('color', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
    ]
