# Generated by Django 5.0.8 on 2026-09-24 12:48

import apps.config_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='nav_links',
            field=models.JSONField(blank=True, default=apps.config_api.models.get_default_nav_links, help_text='Navigation links list'),
        ),
    ]
