# Generated by Django 5.0.8 on 2026-09-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0002_privacyconsent'),
        ('config_api', '0002_siteconfig_nav_links'),
    ]

    operations = [
    ]
