# Generated by Django 5.0.8 on 2026-09-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('image', models.URLField(blank=True, help_text='URL to product image', max_length=500, null=True)),
                ('description', models.TextField()),
                ('live_url', models.URLField(blank=True, max_length=500, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features')),
                ('solutions', models.JSONField(blank=True, default=list, help_text='List of solutions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
